// apps/react/src/components/reference.tsx
export function Reference() {
  return (
    <>
      <dl>
        <dt>5′s</dt>
        <dd>50 point</dd>
        <dt>1′s</dt>
        <dd>100 points</dd>
        <dt>1,1,1</dt>
        <dd>300 points</dd>
        <dt>2,2,2</dt>
        <dd>200 points</dd>
        <dt>3,3,3</dt>
        <dd>300 points</dd>
        <dt>4,4,4</dt>
        <dd>400 points</dd>
        <dt>5,5,5</dt>
        <dd>500 points</dd>
        <dt>6,6,6</dt>
        <dd>600 points</dd>
        <dt>Four of a Kind</dt>
        <dd>1,000 points</dd>
        <dt>Five of a Kind</dt>
        <dd>2,000 points</dd>
        <dt>Six of a Kind</dt>
        <dd>3,000 points</dd>
        <dt>A Straight of 1-6</dt>
        <dd>1,500 points</dd>
        <dt>Three Pairs</dt>
        <dd>1,500 points</dd>
        <dt>Four of a Kind + a Pair</dt>
        <dd>1,500</dd>
        <dt>Two sets of Three of a Kind</dt>
        <dd>2,500</dd>
      </dl>
    </>
  );
}

// apps/angular/src/app/components/reference/reference.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'fsc-reference',
  templateUrl: './reference.component.html',
  styleUrls: ['./reference.component.scss'],
})
export class ReferenceComponent {}

<dl>
  <dt>5′s</dt>
  <dd>50 point</dd>
  <dt>1′s</dt>
  <dd>100 points</dd>
  <dt>1,1,1</dt>
  <dd>300 points</dd>
  <dt>2,2,2</dt>
  <dd>200 points</dd>
  <dt>3,3,3</dt>
  <dd>300 points</dd>
  <dt>4,4,4</dt>
  <dd>400 points</dd>
  <dt>5,5,5</dt>
  <dd>500 points</dd>
  <dt>6,6,6</dt>
  <dd>600 points</dd>
  <dt>Four of a Kind</dt>
  <dd>1,000 points</dd>
  <dt>Five of a Kind</dt>
  <dd>2,000 points</dd>
  <dt>Six of a Kind</dt>
  <dd>3,000 points</dd>
  <dt>A Straight of 1-6</dt>
  <dd>1,500 points</dd>
  <dt>Three Pairs</dt>
  <dd>1,500 points</dd>
  <dt>Four of a Kind + a Pair</dt>
  <dd>1,500</dd>
  <dt>Two sets of Three of a Kind</dt>
  <dd>2,500</dd>
</dl>
