// apps/angular/src/app/components/modal/modal.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'fsc-modal',
    templateUrl: './modal.component.html',
    styleUrls: ['./modal.component.scss'],
})
export class ModalComponent {
    title = 'modal title';
}

<div class="modal-backdrop show"></div>
<div class="modal d-block">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{{ title }}</h5>
      </div>
      <div class="modal-body">
        <ng-content></ng-content>
      </div>
    </div>
  </div>
</div>

// apps/react/src/components/modal.js
import React from 'react';

export function Modal(props) {
    return (
        <div classNameName="modal" tabindex="-1">
            <div className="modal-dialog">
                <div className="modal-content">
                    <div className="modal-header">
                        <h5 className="modal-title">{props.title}</h5>
                    </div>
                    <div className="modal-body">
                        {props.children}
                    </div>
                </div>
            </div>
        </div>
    );
}
