// apps/angular/src/app/pages/play/play.component.ts
import { Component } from '@angular/core';
import { Scorecard } from '@fsc/types';
import { Store } from '@ngrx/store';
@Component({
    selector: 'fsc-play',
    templateUrl: './play.component.html',
    styleUrls: ['./play.component.scss'],
})
export class PlayComponent {
    players: string[] = [];
    scores: {
        [key: string]: Scorecard;
    };
    error = false;

    constructor(private store: Store<{ players: { players: string[] } }>) {
        this.store.subscribe((state) => {
            this.players = state.players.players;
        });
    }
}

<div>
    <h2>Scorecard</h2>
    <div *ngIf="gameOver && winnerName"
         class="winner-banner">
        {{ winnerName }} wins with {{ scores[winnerName]?.total }} points!
    </div>
    <div *ngIf="finalRound && !gameOver"
         class="final-round-banner">
        Final round! {{ winnerName }} reached {{ winScore }}. Everyone else gets one last turn.
    </div>
    <div *ngIf="error"
         class="alert alert-danger"
         role="alert">Score must be a number</div>
    <div *ngIf="!gameOver">
        <fsc-edit-player-score [player]="players[currentPlayer]"
                               (saveScorecard)="handleSetScore($event)" />
    </div>
    <div *ngIf="gameOver">
        <h3>Game Over!</h3>
    </div>
    <button *ngIf="lastActionPlayer && !gameOver"
            class="btn btn-outline-warning btn-sm mb-3"
            (click)="handleUndo()">
        Undo Last Score
    </button>
    <div *ngFor="let player of players"
         class="row mb-5">
        <fsc-player-score [player]="player"
                          [scorecard]="getScorecard(player)"
                          [isCurrentPlayer]="player === players[currentPlayer] && !gameOver" />
    </div>
</div>

// apps/react/src/pages/play.tsx
import { type Scores } from '@fsc/types';
import { EditPlayerScore } from '../components/game/edit-player-score';
import { PlayerScore } from '../components/game/player-score';
import { useState } from 'react';

interface PlayProps {
    players: string[];
    scorecards: Scores;
    setScorecards: (player: string, score: number) => void;
    onFinalRoundCheck: (currentPlayer: string) => void;
    gameOver: boolean;
    canUndo: boolean;
    onUndo: () => void;
}

export function Play({
    players,
    scorecards,
    setScorecards,
    onFinalRoundCheck,
    gameOver,
    canUndo,
    onUndo,
}: PlayProps) {
    const [selectedPlayer, setSelectedPlayer] = useState(players[0]);
    const [error, setError] = useState(false);

    function handleSetScore(newScore: number) {
        if (!isNaN(newScore)) {
            setScorecards(selectedPlayer, newScore);
            setError(false);
            handleNextPlayer();
        } else {
            setError(true);
        }
    }

    function handleNextPlayer() {
        const recentPlayerIndex = players.indexOf(selectedPlayer);
        let nextIndex: number;
        if (recentPlayerIndex === players.length - 1) {
            nextIndex = 0;
        } else {
            nextIndex = recentPlayerIndex + 1;
        }
        const nextPlayer = players[nextIndex];
        setSelectedPlayer(nextPlayer);

        // Check if the final round has come back around
        onFinalRoundCheck(nextPlayer);
    }

    function renderPlayers() {
        return players.map((player) => (
            <div className="col-sm" key={player}>
                <PlayerScore
                    player={player}
                    scorecard={scorecards[player]}
                    isCurrentPlayer={player === selectedPlayer && !gameOver}
                />
            </div>
        ));
    }

    function renderCurrentPlayer() {
        if (gameOver) {
            return <h3>Game Over!</h3>;
        }
        if (selectedPlayer) {
            return (
                <EditPlayerScore
                    player={selectedPlayer}
                    scorecard={scorecards[selectedPlayer]}
                    handleSave={handleSetScore}
                />
            );
        } else {
            return <h3>no player selected</h3>;
        }
    }

    function renderError() {
        return (
            <div className="alert alert-danger" role="alert">
                Score must be a number
            </div>
        );
    }

    return (
        <div>
            <h2>Scorecard</h2>
            {error ? renderError() : null}
            {renderCurrentPlayer()}
            {canUndo && !gameOver && (
                <button className="btn btn-outline-warning btn-sm mb-3" onClick={onUndo}>
                    Undo Last Score
                </button>
            )}
            <div className="row mb-5">{renderPlayers()}</div>
        </div>
    );
}
