// apps/angular/src/app/pages/setup/setup.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-setup',
  templateUrl: './setup.component.html',
  styleUrls: ['./setup.component.scss']
})
export class SetupComponent {

}

<h2>Add Players</h2>
<div class="row players">
    <div class="col-12">
        <fsc-add-player (addPlayer)="handleAddPlayer($event)" />
    </div>
</div>
<div class="row">
    <div class="col-12">
        <fsc-player *ngFor="let player of players"
                    [player]="player"
                    (editPlayer)="handleEditPlayer($event)"
                    (removePlayer)="handleRemovePlayer($event)" />
    </div>
</div>
<div class="row mb-3">
    <div class="col-12">
        <label for="onBoardThreshold"
               class="form-label">Points needed to get on the board</label>
        <select id="onBoardThreshold"
                class="form-select"
                [ngModel]="onBoardThreshold"
                (ngModelChange)="handleThresholdChange($event)">
            <option value="500">500 (Standard)</option>
            <option value="750">750</option>
            <option value="1000">1000</option>
        </select>
    </div>
</div>
<button class="btn btn-success"
        [disabled]="players.length < 2"
        (click)="play()">Start Game</button>

// apps/react/src/pages/setup.js
import React, { useState } from 'react';

import { AddPlayer } from '../components/setup/add-player';
import { Player } from '../components/setup/player';

export function Setup(props) {
    const [players, setPlayers] = useState([]);

    function handleAddPlayer(newPlayer) {
        setPlayers([newPlayer, ...players]);
    };

    function handleSavePlayers() {
        props.setPlayers(players);
    }

    function handleEditPlayer(oldPlayer, newPlayer) {
        const newPlayers = players.slice();
        const index = players.indexOf(oldPlayer);
        newPlayers[index] = newPlayer;
        setPlayers(newPlayers);
    }

    function handleRemovePlayer(oldPlayer) {
        const newPlayers = players.slice();
        const index = players.indexOf(oldPlayer);
        newPlayers.splice(index, 1);
        setPlayers(newPlayers);
    }

    function renderPlayers() {
        return players.map((player) => (
            <Player key={player}
                player={player}
                handleEdit={handleEditPlayer}
                handleRemove={handleRemovePlayer} />
        ));
    }

    return (
        <div>
            <h2>Add Players</h2>
            <div className="row players">
                <div className="col-12">
                    <AddPlayer handleSave={handleAddPlayer} />
                </div>
            </div>
            <div className="row">
                <div className="col-12">
                    {renderPlayers()}
                </div>
            </div>
            <button
                className="btn btn-success"
                disabled={players.length <= 1}
                onClick={handleSavePlayers}>
                Start Game
            </button>
        </div>
    )
}
