// apps/angular/src/app/components/edit-player-score/edit-player-score.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Player, Scorecard } from '@fsc/types';

@Component({
    selector: 'fsc-edit-player-score',
    templateUrl: './edit-player-score.component.html',
    styleUrls: ['./edit-player-score.component.scss'],
})
export class EditPlayerScoreComponent {
    @Input() player: Player = '';
    @Input() scorecard: Scorecard;

    @Output()
    saveScorecard = new EventEmitter<Scorecard>();

    score = 0;

    save() {
        this.saveScorecard.emit(this.scorecard);
    }
}

<div [ngClass]="{ 'on-board': scorecard.onBoard }">
    <h3>{{ player }}</h3>
    <div class="input-group mb-3">
        <input
            type="text"
            name="score"
            class="form-control"
            placeholder="Score"
            aria-label="Score"
            [(ngModel)]="score"
        />
        <div class="input-group-append">
            <button class="btn btn-success" type="submit" id="button-addon2" (click)="save()">
                Save
            </button>
        </div>
    </div>
</div>

// apps/react/src/components/game/edit-player-score.js
import React, { useState } from 'react';

export function EditPlayerScore(props) {
    const player = props.player;
    const scorecard = props.scorecard;
    const [value, setValue] = useState('');

    function handleInputUpdate(event) {
        setValue(event.target.value);
    }

    function handleSetScore(event) {
        event.preventDefault();
        props.handleSave(value);
        setValue('');
    };

    return (
        <div key={player}
            className={scorecard.onBoard ? 'on-board' : 'off-board'}>
            <h3>{player}</h3>
            <form>
                <div className="input-group mb-3">
                    <input
                        type="text"
                        name="score"
                        className="form-control" placeholder="Score"
                        aria-label="Score"
                        value={value}
                        onChange={handleInputUpdate} />
                    <div className="input-group-append">
                        <button
                            className="btn btn-success"
                            type="submit"
                            id="button-addon2"
                            onClick={handleSetScore}>
                            Save
                        </button>
                    </div>
                </div>
            </form>
        </div>
    )
}
