// apps/angular/src/app/components/player-score/player-score.component.ts
import { Component, Input } from '@angular/core';
import { Player, Scorecard } from '@fsc/types';

@Component({
    selector: 'fsc-player-score',
    templateUrl: './player-score.component.html',
    styleUrls: ['./player-score.component.scss'],
})
export class PlayerScoreComponent {
    @Input() player: Player = '';
    @Input() scorecard: Scorecard;
}

<div class="card"
     [ngClass]="{ 'on-board': scorecard?.onBoard, 'current-player': isCurrentPlayer, 'leader': isLeader }"
     key="{player}">
    <div class="card-body">
        <div *ngIf="!scorecard?.onBoard && scorecard?.total === 0"
             class="alert alert-warning"
             role="alert">
            A score of 500 is needed in one roll to be on the board.
        </div>
        <h5 class="card-title">
            {{ player }}
            <span *ngIf="isLeader"
                  class="badge bg-warning text-dark ms-2">Leader</span>
        </h5>
        <p class="card-text">Total: {{ scorecard?.total }}</p>
        <div *ngIf="!!scorecard?.turns?.length">
            <h6>Turn History</h6>
            <ul class="list-group list-group-flush">
                <li *ngFor="let turn of scorecard?.turns"
                    class="list-group-item"
                    [ngClass]="{ 'farkle-turn': turn === 0 }">
                    {{ turn === 0 ? 'FARKLE!' : turn }}
                </li>
            </ul>
        </div>
    </div>
</div>

// apps/react/src/components/game/player-score.tsx
import { type Scorecard } from '@fsc/types';
import classNames from 'classnames';

interface PlayerScoreProps {
    player: string;
    scorecard: Scorecard;
    isCurrentPlayer?: boolean;
    isLeader?: boolean;
}

export function PlayerScore({
    player,
    scorecard,
    isCurrentPlayer = false,
    isLeader = false,
}: PlayerScoreProps) {
    function renderBoardMessages() {
        if (scorecard.total === 0 && !scorecard.onBoard) {
            return (
                <div className="alert alert-warning" role="alert">
                    A score of 500 is needed in one roll to be on the board.
                </div>
            );
        }
    }

    function renderTurnHistory() {
        if (scorecard.turns.length >= 1) {
            const turnList = scorecard.turns.map((turn, index) => {
                const key = `${player}-turn-${index}`;
                return (
                    <li
                        className={classNames('list-group-item', {
                            'farkle-turn': turn === 0,
                        })}
                        key={key}
                    >
                        {turn === 0 ? 'FARKLE!' : turn}
                    </li>
                );
            });

            return (
                <div>
                    <h6>Turn History</h6>
                    <ul className="list-group list-group-flush">{turnList}</ul>
                </div>
            );
        }
    }

    return (
        <div
            className={classNames('card', {
                'on-board': scorecard.onBoard,
                'current-player': isCurrentPlayer,
                leader: isLeader,
            })}
            key={player}
        >
            <div className="card-body">
                {renderBoardMessages()}
                <h5 className="card-title">
                    {player}
                    {isLeader && <span className="badge bg-warning text-dark ms-2">Leader</span>}
                </h5>
                <p className="card-text">Total: {scorecard.total}</p>
                {renderTurnHistory()}
            </div>
        </div>
    );
}
