// apps/angular/src/app/components/add-player/add-player.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
    selector: 'fsc-add-player',
    templateUrl: './add-player.component.html',
    styleUrls: ['./add-player.component.scss'],
})
export class AddPlayerComponent {
    @Output()
    addPlayer = new EventEmitter<string>();

    name = '';

    save(): void {
        this.addPlayer.emit(this.name);
        this.name = '';
    }
}

<form>
    <div class="input-group mb-3">
        <input type="text"
               name="player"
               class="form-control"
               placeholder="Player"
               aria-label="Player"
               value={value}
               onChange={handleInputUpdate} />
        <div class="input-group-append">
            <button class="btn btn-secondary"
                    type="submit"
                    id="button-addon2"
                    onClick={handleAddPlayer}>
                Add
            </button>
        </div>
    </div>
</form>

// apps/react/src/components/setup/add-player.tsx
import { BaseSyntheticEvent, useState } from 'react';

interface AddPlayerProps {
  handleSave: (player: string) => void;
}

export function AddPlayer({ handleSave }: AddPlayerProps) {
  const [value, setValue] = useState('');

  const handleInputUpdate = (event: BaseSyntheticEvent) => {
    setValue(event.target.value);
  };

  const handleAddPlayer = (event: BaseSyntheticEvent) => {
    event.preventDefault();
    handleSave(value);
    setValue('');
  };

  return (
    <form>
      <div className="input-group mb-3">
        <input
          type="text"
          name="player"
          className="form-control"
          placeholder="Player"
          aria-label="Player"
          value={value}
          onChange={handleInputUpdate}
        />
        <div className="input-group-append">
          <button
            className="btn btn-secondary"
            type="submit"
            id="button-addon2"
            onClick={handleAddPlayer}
          >
            Add
          </button>
        </div>
      </div>
    </form>
  );
}
