// apps/react/src/pages/setup.tsx
import { addPlayerReducer, editPlayerReducer, removePlayerReducer } from '@fsc/state';
import { Players } from '@fsc/types';
import { AddPlayer } from '../components/setup/add-player';
import { PlayerName } from '../components/setup/player';
import { type BaseSyntheticEvent, useState } from 'react';

interface SetupProps {
    setGamePlayers: (allPlayers: Players) => void;
    onBoardThreshold: number;
    setOnBoardThreshold: (threshold: number) => void;
}

export function Setup({ setGamePlayers, onBoardThreshold, setOnBoardThreshold }: SetupProps) {
    const [players, setPlayers] = useState([] as string[]);

    function handleAddPlayer(newPlayer: string) {
        setPlayers(addPlayerReducer({ players, newPlayer }));
    }

    function handleSavePlayers() {
        setGamePlayers(players);
    }

    function handleEditPlayer(oldPlayer: string, newPlayer: string) {
        setPlayers(editPlayerReducer({ players, oldPlayer, newPlayer }));
    }

    function handleRemovePlayer(player: string) {
        setPlayers(removePlayerReducer({ players, player }));
    }

    function handleThresholdChange(event: BaseSyntheticEvent) {
        setOnBoardThreshold(Number(event.target.value));
    }

    function renderPlayers() {
        return players.map((player) => (
            <PlayerName
                key={player}
                player={player}
                handleEdit={handleEditPlayer}
                handleRemove={handleRemovePlayer}
            />
        ));
    }

    return (
        <div>
            <h2>Add Players</h2>
            <div className="row players">
                <div className="col-12">
                    <AddPlayer handleSave={handleAddPlayer} />
                </div>
            </div>
            <div className="row">
                <div className="col-12">{renderPlayers()}</div>
            </div>
            <div className="row mb-3">
                <div className="col-12">
                    <label htmlFor="onBoardThreshold" className="form-label">
                        Points needed to get on the board
                    </label>
                    <select
                        id="onBoardThreshold"
                        className="form-select"
                        value={onBoardThreshold}
                        onChange={handleThresholdChange}
                    >
                        <option value={500}>500 (Standard)</option>
                        <option value={750}>750</option>
                        <option value={1000}>1000</option>
                    </select>
                </div>
            </div>
            <button
                className="btn btn-success"
                disabled={players.length <= 1}
                onClick={handleSavePlayers}
            >
                Start Game
            </button>
        </div>
    );
}

// apps/angular/src/app/pages/setup/setup.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { DEFAULT_ON_BOARD_THRESHOLD } from '@fsc/types';
import { Store } from '@ngrx/store';
import { initScores, setOnBoardThreshold } from 'app/store/game/game.actions';

import { addPlayer, editPlayer, removePlayer } from 'app/store/players/players.actions';

@Component({
    selector: 'fsc-setup',
    standalone: false,
    templateUrl: './setup.component.html',
    styleUrls: ['./setup.component.scss'],
})
export class SetupComponent {
    players: string[] = [];
    onBoardThreshold = DEFAULT_ON_BOARD_THRESHOLD;

    constructor(
        private store: Store<{ players: { players: string[] } }>,
        private router: Router
    ) {
        this.store.subscribe((state) => {
            this.players = state.players.players;
        });
    }

    handleAddPlayer(newPlayer: string): void {
        this.store.dispatch(addPlayer({ newPlayer }));
    }

    handleEditPlayer({ oldPlayer, newPlayer }: { oldPlayer: string; newPlayer: string }): void {
        this.store.dispatch(editPlayer({ oldPlayer, newPlayer }));
    }

    handleRemovePlayer(player: string): void {
        this.store.dispatch(removePlayer({ player }));
    }

    handleThresholdChange(value: string): void {
        this.onBoardThreshold = Number(value);
        this.store.dispatch(setOnBoardThreshold({ threshold: this.onBoardThreshold }));
    }

    play(): void {
        this.store.dispatch(initScores({ players: this.players }));
        this.router.navigateByUrl('play');
    }
}

<h2>Add Players</h2>
<div class="row players">
    <div class="col-12">
        <fsc-add-player (addPlayer)="handleAddPlayer($event)" />
    </div>
</div>
<div class="row">
    <div class="col-12">
        <fsc-player *ngFor="let player of players"
                    [player]="player"
                    (editPlayer)="handleEditPlayer($event)"
                    (removePlayer)="handleRemovePlayer($event)" />
    </div>
</div>
<div class="row mb-3">
    <div class="col-12">
        <label for="onBoardThreshold"
               class="form-label">Points needed to get on the board</label>
        <select id="onBoardThreshold"
                class="form-select"
                [ngModel]="onBoardThreshold"
                (ngModelChange)="handleThresholdChange($event)">
            <option value="500">500 (Standard)</option>
            <option value="750">750</option>
            <option value="1000">1000</option>
        </select>
    </div>
</div>
<button class="btn btn-success"
        [disabled]="players.length < 2"
        (click)="play()">Start Game</button>
