// apps/angular/src/app/components/player-score/player-score.component.ts
import { Component, Input } from '@angular/core';
import { Player, Scorecard } from '@fsc/types';

@Component({
    selector: 'fsc-player-score',
    standalone: false,
    templateUrl: './player-score.component.html',
    styleUrls: ['./player-score.component.scss'],
})
export class PlayerScoreComponent {
    @Input() player: Player = '';
    @Input() scorecard: Scorecard;
    @Input() isCurrentPlayer = false;
}

<div class="card"
     [ngClass]="{ 'on-board': scorecard?.onBoard, 'current-player': isCurrentPlayer }"
     key="{player}">
    <div class="card-body">
        <div *ngIf="!scorecard?.onBoard && scorecard?.total === 0"
             class="alert alert-warning"
             role="alert">
            A score of 500 is needed in one roll to be on the board.
        </div>
        <h5 class="card-title">{{ player }}</h5>
        <p class="card-text">Total: {{ scorecard?.total }}</p>
        <div *ngIf="!!scorecard?.turns?.length">
            <h6>Turn History</h6>
            <ul class="list-group list-group-flush">
                <li *ngFor="let turn of scorecard?.turns"
                    class="list-group-item"
                    [ngClass]="{ 'farkle-turn': turn === 0 }">
                    {{ turn === 0 ? 'FARKLE!' : turn }}
                </li>
            </ul>
        </div>
    </div>
</div>

// react/src/components/game/player-score.js
import React from 'react';
import classNames from 'classnames';

export function PlayerScore(props) {
    const player = props.player;
    const scorecard = props.scorecard;

    function renderBoardMessages() {
        if (scorecard.total === 0) {
            return (
                <div className="alert alert-warning" role="alert">
                    A score of 500 is needed in one roll to be on the board.
                </div>
            )
        }
    }

    return (
        <div className={classNames('card', {
            'on-board': scorecard.onBoard
        })} key={player}>
            <div className="card-body">
                {renderBoardMessages()}
                <h5 className="card-title">{player}</h5>
                <p className="card-text">Total: {scorecard.total}</p>
            </div>
        </div>
    )
}
