// apps/react/src/components/nav.tsx
import { ReactNode } from 'react';

export function Nav({ children }: { children: ReactNode }) {
  return (
    <nav className="position-sticky navbar navbar-expand navbar-dark bg-dark">
      <div className="container-fluid">
        <span className="navbar-brand">Farkle Scorecard</span>
        {children}
      </div>
    </nav>
  );
}

// apps/angular/src/app/components/nav/nav.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'fsc-nav',
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.scss'],
})
export class NavComponent {}

<nav class="position-sticky navbar navbar-expand navbar-dark bg-dark">
  <div class="container-fluid">
    <span class="navbar-brand">Farkle Scorecard</span>
    <ng-content></ng-content>
  </div>
</nav>
