// react/src/components/nav.js
import React from 'react';

export function Nav({ children }) {
    return (
        <nav className="position-sticky navbar navbar-expand-lg navbar-dark bg-dark">
            <span className="navbar-brand">
                Farkle Scorecard
            </span>

            <div className="collapse navbar-collapse" id="navbarSupportedContent">
                {children}
            </div>
        </nav >
    );
}

// angular/src/app/components/nav/nav.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'sc-nav',
    templateUrl: './nav.component.html'
})
export class NavComponent implements OnInit {

    constructor() { }

    ngOnInit(): void {
    }

}

<nav class="position-sticky navbar navbar-expand-lg navbar-dark bg-dark">
    <span class="navbar-brand">
        Farkle Scorecard
    </span>

    <div class="collapse navbar-collapse"
         id="navbarSupportedContent">
        <ng-content></ng-content>
    </div>
</nav>
